DROP IF EXISTS singular_db;
CREATE DATABASE singular_db;
USE singular_db; 

CREATE TABLE users (
    id CHAR(36) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE students (
    id CHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    cpf CHAR(11) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    classroom_group_id CHAR(36) NOT NULL,
    plan_expires_at DATE NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE teachers (
    id CHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    cpf CHAR(11) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE disciplines (
    id CHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    -- discipline_total_load INT NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE,
    available BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE classroom_groups (
    id CHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lessons (
    id CHAR(36) PRIMARY KEY,
    discipline_id CHAR(36) NOT NULL,
    classroom_group_id CHAR(36) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE,
    lesson_type TINYINT UNSIGNED NOT NULL COMMENT '0=THEORICAL, 1=PRACTICAL, 2=REPLACEMENT, 3=EVALUATIVE',
    status TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0=PENDING, 1=MINISTERED, 2=CANCELED',
    content TEXT NOT NULL,
    local VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_lesson_discipline FOREIGN KEY (discipline_id) REFERENCES disciplines(id) ON DELETE CASCADE,
    CONSTRAINT fk_lesson_classroom FOREIGN KEY (classroom_group_id) REFERENCES classroom_groups(id) ON DELETE CASCADE
);
